# Generated by Django 5.1.5 on 2025-02-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='product_qty',
        ),
    ]
