# Generated by Django 5.1.5 on 2025-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_message_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_model',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/'),
        ),
    ]
