# Generated by Django 5.1.5 on 2025-03-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_ar_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ar_model',
        ),
    ]
